# Generated by Django 5.1.1 on 2025-09-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatprofile',
            name='style_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='marketplace.item'),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.chatprofile'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='chat_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile_inventory', to='main.chatprofile'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.item'),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatmember'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(to='main.interes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.chatprofilestyle'),
        ),
    ]
