# Generated by Django 5.1.1 on 2025-09-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chatprofile_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_profile',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='events',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='chatprofile',
            name='style_item',
        ),
        migrations.AddField(
            model_name='achievement',
            name='chat_profile',
            field=models.ManyToManyField(related_name='achievements', to='main.chatprofile'),
        ),
        migrations.AddField(
            model_name='chatprofile',
            name='chat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='chat_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='main.chatprofile'),
        ),
    ]
