# Generated by Django 5.1.1 on 2025-09-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('emotion', 'Emotion'), ('message', 'Message'), ('profile', 'Profile'), ('gallery', 'Gallery')], max_length=30)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('exotic', 'Exotic'), ('divine', 'Divine'), ('celestial', 'Celestial'), ('unique', 'Unique')], max_length=12)),
                ('price', models.IntegerField()),
                ('special_type', models.CharField(choices=[('none', 'None'), ('friend', 'Friend'), ('love', 'Love')], max_length=6)),
                ('is_tradeable', models.BooleanField(default=True)),
                ('release_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/gallery_style/')),
                ('border', models.ImageField(upload_to='items/gallery_style/')),
                ('font_style', models.CharField(max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='marketplace.item')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/emotion/')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to='marketplace.item')),
            ],
        ),
        migrations.CreateModel(
            name='ChatProfileStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='items/chat_profile_style/')),
                ('header', models.ImageField(upload_to='items/chat_profile_style/')),
                ('font_style', models.CharField(max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='marketplace.item')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('love coin', 'Love coin'), ('friend coin', 'Friend coin'), ('any coin', 'Any coin')], max_length=11)),
                ('reason', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('love coin', 'Love coin'), ('friend coin', 'Friend coin'), ('any coin', 'Any coin')], max_length=11)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], max_length=9)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventory')),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='items/message_style/')),
                ('border', models.ImageField(upload_to='items/message_style/')),
                ('font_style', models.CharField(max_length=50)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='marketplace.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_each_cached', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=8)),
                ('buyers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.listing')),
            ],
        ),
    ]
