# Generated by Django 5.1.1 on 2025-09-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('main', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(related_name='members', to='main.chatprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.events'),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='award_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.item'),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
