# Generated by Django 5.1.1 on 2025-09-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='chat_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to='main.chatprofile'),
        ),
        migrations.AddField(
            model_name='memory',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chatmember'),
        ),
        migrations.AddField(
            model_name='memory',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
