# Generated by Django 5.1.1 on 2025-09-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_initial'),
        ('main', '0006_remove_chat_chat_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='chat_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='main.chatprofile'),
        ),
    ]
